#!/usr/bin/env python3
"""Turn the host's CA bundle into a C table the kernel can carry.

A certificate is only worth checking against something you already trust, and
that "something" has to come from somewhere. It comes from here: the same list
of root authorities the host system uses, frozen into the kernel image."""
import base64, re, sys
import os

# Where things are. The project is found from this file's own location, so a
# checkout anywhere works; the scratch area where NetSurf and Lexbor sources
# are unpacked defaults to ~/src. Both can be overridden by environment.
XYUOS = os.environ.get(
    "XYUOS", os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
XYUOS_SRC = os.environ.get(
    "XYUOS_SRC", os.path.join(os.path.expanduser("~"), "src"))

src = "/etc/ssl/certs/ca-certificates.crt"
out = XYUOS + "/kernel/net/roots.h"

pem = open(src).read()
blocks = re.findall(r"-----BEGIN CERTIFICATE-----(.*?)-----END CERTIFICATE-----", pem, re.S)
ders = [base64.b64decode(b) for b in blocks]
if not ders:
    sys.exit("no certificates in " + src)

blob = b"".join(ders)
idx, off = [], 0
for d in ders:
    idx.append((off, len(d)))
    off += len(d)

lines = []
lines.append("/* Generated by tools/genroots.py from %s -- do not edit.\n"
             " *\n"
             " * The root certificate authorities this system trusts: %d of them,\n"
             " * %d bytes of DER. A chain is only believed if it ends at one of\n"
             " * these. Regenerate to follow the host's bundle. */\n"
             % (src, len(ders), len(blob)))
lines.append("static const uint8_t ROOT_DER[%d] = {" % len(blob))
row = "   "
for i, b in enumerate(blob):
    tok = "0x%02x," % b
    if len(row) + len(tok) > 76:
        lines.append(row); row = "   "
    row += tok
lines.append(row)
lines.append("};\n")

lines.append("static const struct { unsigned int off, len; } ROOT_IDX[%d] = {" % len(idx))
row = "   "
for o, l in idx:
    tok = " {%d,%d}," % (o, l)
    if len(row) + len(tok) > 76:
        lines.append(row); row = "   "
    row += tok
lines.append(row)
lines.append("};\n")
lines.append("#define ROOT_COUNT %d\n" % len(idx))

open(out, "w").write("\n".join(lines))
print("wrote %s: %d roots, %d bytes" % (out, len(ders), len(blob)))
