#!/usr/bin/env python3
"""Generate known-answer vectors for the kernel's crypto self-test from a
library that is known good, so the test proves our code and not our memory."""
import hashlib, hmac
from cryptography.hazmat.primitives.asymmetric.x25519 import X25519PrivateKey
from cryptography.hazmat.primitives.serialization import (
    Encoding, PublicFormat, PrivateFormat, NoEncryption)
from cryptography.hazmat.primitives.ciphers.aead import AESGCM

def carr(name, b):
    body = ", ".join("0x%02x" % c for c in b)
    lines, cur = [], "    "
    for tok in body.split(", "):
        if len(cur) + len(tok) + 2 > 76:
            lines.append(cur.rstrip()); cur = "    "
        cur += tok + ", "
    lines.append(cur.rstrip().rstrip(","))
    return "static const uint8_t %s[%d] = {\n%s\n};\n" % (name, len(b), "\n".join(lines))

out = []

# --- SHA-256 over more than one block -------------------------------------
msg = bytes((i * 7 + 3) & 0xFF for i in range(1000))
out.append(carr("v_sha_msg", msg))
out.append(carr("v_sha_out", hashlib.sha256(msg).digest()))

# --- HMAC ------------------------------------------------------------------
hk, hd = bytes(range(1, 41)), b"the quick brown fox jumps over the lazy dog"
out.append(carr("v_hmac_key", hk))
out.append(carr("v_hmac_msg", hd))
out.append(carr("v_hmac_out", hmac.new(hk, hd, hashlib.sha256).digest()))

# --- HKDF-Expand-Label, exactly as RFC 8446 5.3 defines it -----------------
def expand(prk, info, n):
    t, okm, c = b"", b"", 1
    while len(okm) < n:
        t = hmac.new(prk, t + info + bytes([c]), hashlib.sha256).digest()
        okm += t; c += 1
    return okm[:n]

def expand_label(secret, label, ctx, n):
    lab = b"tls13 " + label
    info = n.to_bytes(2, "big") + bytes([len(lab)]) + lab + bytes([len(ctx)]) + ctx
    return expand(secret, info, n)

secret = bytes((i * 11 + 5) & 0xFF for i in range(32))
ctxh   = hashlib.sha256(b"transcript").digest()
out.append(carr("v_hkdf_secret", secret))
out.append(carr("v_hkdf_ctx", ctxh))
out.append(carr("v_hkdf_key", expand_label(secret, b"key", ctxh, 16)))
out.append(carr("v_hkdf_long", expand_label(secret, b"c ap traffic", ctxh, 48)))

# --- X25519 ----------------------------------------------------------------
apriv = bytes.fromhex("77076d0a7318a57d3c16c17251b26645df4c2f87ebc0992ab177fba51db92c2a")
bpriv = bytes.fromhex("5dab087e624a8a4b79e17f8b83800ee66f3bb1292618b6fd1c2f8b27ff88e0eb")
ak = X25519PrivateKey.from_private_bytes(apriv)
bk = X25519PrivateKey.from_private_bytes(bpriv)
apub = ak.public_key().public_bytes(Encoding.Raw, PublicFormat.Raw)
bpub = bk.public_key().public_bytes(Encoding.Raw, PublicFormat.Raw)
shared = ak.exchange(bk.public_key())
out.append(carr("v_x_apriv", apriv))
out.append(carr("v_x_apub", apub))
out.append(carr("v_x_bpriv", bpriv))
out.append(carr("v_x_bpub", bpub))
out.append(carr("v_x_shared", shared))

# --- AES-128-GCM -----------------------------------------------------------
key   = bytes.fromhex("feffe9928665731c6d6a8f9467308308")
nonce = bytes.fromhex("cafebabefacedbaddecaf888")
aad   = bytes.fromhex("feedfacedeadbeeffeedfacedeadbeefabaddad2")
pt    = bytes((i * 5 + 1) & 0xFF for i in range(53))
ct    = AESGCM(key).encrypt(nonce, pt, aad)
out.append(carr("v_gcm_key", key))
out.append(carr("v_gcm_nonce", nonce))
out.append(carr("v_gcm_aad", aad))
out.append(carr("v_gcm_pt", pt))
out.append(carr("v_gcm_ct", ct[:-16]))
out.append(carr("v_gcm_tag", ct[-16:]))

# an empty plaintext with no AAD, which is only a tag
ct0 = AESGCM(bytes(16)).encrypt(bytes(12), b"", b"")
out.append(carr("v_gcm_empty_tag", ct0))

open("/tmp/crypto_vectors.h", "w").write(
    "/* Generated by tools/genvec.py -- do not edit.\n"
    " * Known answers from a reference implementation, so the self-test checks\n"
    " * our code rather than our recollection of the standards. */\n\n"
    + "\n".join(out))
print("wrote /tmp/crypto_vectors.h")
