#!/usr/bin/env python3
"""Build NetSurf's parser, CSS and DOM libraries as archives for xyuOS.

The tarballs ship four files that are made rather than written -- the HTML
entity table, the encoding aliases, and a perfect hash of element names -- and
their own build system makes them with perl and gperf on the host. That part
is not porting; it is running two scripts. Everything after it is compiled
with xyuOS's cross toolchain against xyuOS's own libc.
"""
import os, subprocess, sys

HOME = "/home/roman/xyuos-neo"
NS = "/home/roman/src/ns"
CC = HOME + "/toolchain/cross/bin/x86_64-elf-gcc"
AR = HOME + "/toolchain/cross/bin/x86_64-elf-ar"
OUT = HOME + "/third_party/netsurf"

LIBS = ["libwapcaplet-0.4.3", "libparserutils-0.2.4", "libhubbub-0.3.8",
        "libcss-0.9.1", "libdom-0.4.2",
        # The core reaches for this one for the time of day and a couple of
        # other things the platform is supposed to answer.
        "libnsutils-0.1.0",
        # A BMP and ICO decoder, and the character tables that decide what a
        # domain name in a language other than English comes to.
        "libnsbmp-0.1.6", "libutf8proc-2.4.0-1"]

# The one file that wants a real iconv. libparserutils has its own codecs for
# everything a page is actually written in, and its build only compiles this
# one when asked for it.
# Not translation units: a table of data that a source file includes into
# itself. Compiling it on its own asks it to stand up without the header that
# gives its types names.
SKIP = ["src/utf8proc_data.c"]

# Source directories beyond src/. libdom keeps its bridges to the parsers in
# bindings/ -- without the hubbub one there is a DOM and an HTML parser and
# nothing joining them. The xml binding wants libxml2 and is left alone.
EXTRA_DIRS = {"libdom-0.4.2": ["bindings/hubbub"]}

FLAGS = ["-ffreestanding", "-fno-stack-protector", "-fno-pic", "-fno-pie",
         "-mno-red-zone", "-msse", "-msse2", "-std=gnu11", "-O2", "-g", "-w",
         # libparserutils reaches for the system iconv unless told not to. Its
         # own codecs cover everything a page is written in.
         "-DWITHOUT_ICONV_FILTER",
         # libcss ends a struct with `} _ALIGNED;` and defines _ALIGNED
         # nowhere in its tree -- so instead of an alignment attribute it
         # declares a variable of that name in every file that includes
         # the header, and the linker refuses them all. Defining it as
         # nothing is what the line was written to mean.
         "-D_ALIGNED=",
         # And these sources predate -fno-common being the default.
         "-fcommon"]


def run(cmd, cwd=None):
    r = subprocess.run(cmd, cwd=cwd, capture_output=True, text=True, shell=True)
    if r.returncode != 0:
        print("   ! %s\n     %s" % (cmd, (r.stderr or r.stdout).strip()[:300]))
    return r.returncode == 0


def generate():
    """The four made files, made."""
    pu = NS + "/libparserutils-0.2.4"
    hb = NS + "/libhubbub-0.3.8"

    if not os.path.exists(pu + "/src/charset/aliases.inc"):
        run("perl build/make-aliases.pl", cwd=pu)
    if not os.path.exists(hb + "/src/tokeniser/entities.inc"):
        run("perl build/make-entities.pl", cwd=hb)

    gen = hb + "/src/treebuilder/autogenerated-element-type.c"
    if not os.path.exists(gen):
        # gperf writes a non-static table; their build makes it static so it
        # does not collide at link time. The same sed, done here.
        run("gperf --output-file=%s.tmp src/treebuilder/element-type.gperf" % gen,
            cwd=hb)
        run("sed -e 's/^\\(const struct element_type_map\\)/static \\1/' "
            "%s.tmp > %s && rm -f %s.tmp" % (gen, gen, gen), cwd=hb)

    for f in (pu + "/src/charset/aliases.inc",
              hb + "/src/tokeniser/entities.inc", gen):
        print("   %-58s %s" % (f.replace(NS + "/", ""),
                               "made" if os.path.exists(f) else "MISSING"))

    # libcss writes its own property parsers -- a hundred and nineteen of
    # them, one per CSS property, from one line of description each. The
    # writer is a C program built for the HOST, not for xyuOS: it runs here
    # and never goes near the target.
    cs = NS + "/libcss-0.9.1"
    pdir = cs + "/src/parse/properties"
    genexe = "/home/roman/src/ns/gen_parser"
    if not os.path.exists(genexe):
        run("cc -O1 -w -o %s %s/css_property_parser_gen.c" % (genexe, pdir))

    made = 0
    with open(pdir + "/properties.gen") as f:
        for line in f:
            line = line.rstrip("\n")
            if not line or line.startswith("#"):
                continue
            if ":" not in line:
                continue
            name = line.split(":", 1)[0].strip()
            if not name or not name.replace("_", "").isalnum():
                continue
            out = "%s/autogenerated_%s.c" % (pdir, name)
            if os.path.exists(out):
                made += 1
                continue
            r = subprocess.run([genexe, "-o", out, line],
                               capture_output=True, text=True)
            if r.returncode == 0 and os.path.exists(out):
                made += 1
            else:
                print("   ! %s: %s" % (name, (r.stderr or r.stdout).strip()[:120]))
    print("   %-58s %d made" % ("libcss-0.9.1/src/parse/properties/autogenerated_*.c",
                                made))


STAGE = OUT + "/include"


def stage_headers():
    """Put every library's public headers under one root, in the shape the
    sources expect to find them in -- which is what installing them would
    have done, and what `#include <dom/bindings/hubbub/parser.h>` means."""
    import shutil
    if os.path.isdir(STAGE):
        shutil.rmtree(STAGE)
    os.makedirs(STAGE, exist_ok=True)
    for l in LIBS:
        src = "%s/%s/include" % (NS, l)
        if os.path.isdir(src):
            for entry in os.listdir(src):
                s2 = os.path.join(src, entry)
                d2 = os.path.join(STAGE, entry)
                if os.path.isdir(s2):
                    shutil.copytree(s2, d2, dirs_exist_ok=True)
                else:
                    shutil.copy2(s2, d2)
    # libdom's binding headers are not under include/ in the tarball, but
    # that is where everything asks for them.
    b = "%s/libdom-0.4.2/bindings" % NS
    for which in ("hubbub",):
        d = os.path.join(STAGE, "dom", "bindings", which)
        os.makedirs(d, exist_ok=True)
        for f in os.listdir(os.path.join(b, which)):
            if f.endswith(".h"):
                shutil.copy2(os.path.join(b, which, f), os.path.join(d, f))
    print("   headers staged in %s" % STAGE.replace(HOME + "/", ""))


def includes(lib):
    """Its own headers, and only the PUBLIC headers of the others.

    Putting every library's src/ on the path lets one library's private
    header answer another's #include of the same name -- libcss asks for
    "utils/utils.h" and gets libdom's, whose types it has never heard of.
    The errors that come out of that look nothing like their cause."""
    root = "%s/%s" % (NS, lib)
    inc = ["-I" + HOME + "/libc/include",
           "-I" + root + "/include", "-I" + root + "/src", "-I" + root,
           "-I" + STAGE]
    # A library whose public header sits in include/<name>/ includes it
    # unqualified from its own sources, and qualified from everywhere else.
    # Both have to work, so the inner directory goes on its own path too.
    pub = root + "/include"
    if os.path.isdir(pub):
        for entry in sorted(os.listdir(pub)):
            d = os.path.join(pub, entry)
            if os.path.isdir(d):
                inc.append("-I" + d)
    for other in LIBS:
        if other == lib:
            continue
        d = "%s/%s/include" % (NS, other)
        if os.path.isdir(d):
            inc.append("-I" + d)
    return inc


def build(lib):
    inc = includes(lib)
    root = "%s/%s" % (NS, lib)
    objdir = "/home/roman/src/ns/obj/" + lib
    os.makedirs(objdir, exist_ok=True)

    srcs = []
    roots = ["src"] + EXTRA_DIRS.get(lib, [])
    for sub_dir in roots:
        for base, _, files in os.walk(root + "/" + sub_dir):
            for f in sorted(files):
                if not f.endswith(".c"):
                    continue
                rel = os.path.relpath(os.path.join(base, f), root)
                if rel.replace("\\", "/") in SKIP:
                    continue
                srcs.append((rel, os.path.join(base, f)))

    objs, failed = [], []
    for rel, c in srcs:
        o = objdir + "/" + rel.replace("/", "_")[:-2] + ".o"
        r = subprocess.run([CC] + FLAGS + inc + ["-c", c, "-o", o],
                           capture_output=True, text=True)
        if r.returncode == 0:
            objs.append(o)
        else:
            failed.append((rel, r.stderr.strip().splitlines()[:2]))

    name = lib.split("-")[0]
    a = "%s/%s.a" % (OUT, name)
    if objs:
        subprocess.run([AR, "rcs", a] + objs, check=False)
    size = os.path.getsize(a) if os.path.exists(a) else 0
    print("   %-16s %3d objects -> %-42s %7d bytes" %
          (name, len(objs), a.replace(HOME + "/", ""), size))
    for rel, err in failed:
        print("      ! %s" % rel)
        for e in err:
            print("        %s" % e[:150])
    return len(objs), len(failed)


os.makedirs(OUT, exist_ok=True)
print("Making what the build system makes:")
generate()
stage_headers()

print("\nCompiling with the xyuOS cross toolchain:")
tot_ok = tot_bad = 0
for lib in LIBS:
    ok, bad = build(lib)
    tot_ok += ok
    tot_bad += bad

print("\n   %d objects archived, %d files failed" % (tot_ok, tot_bad))
print("   archives in %s" % OUT.replace(HOME + "/", ""))
